name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Build website
        run: |
          npm install
          npm run build
          npm run lint
          npm run test

      - name: Prepare dist directory
        run: |
          mkdir dist_temp
          mv dist/* dist_temp/
          mv dist_temp dist
          shell: bash

      - name: Upload dist directory to artifact store
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist

      - name: Download build artifacts from artifact store
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        run: |
          az storage blob upload-batch --account-name staticcontent1 --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key --overwrite -d '$web' -s dist/*

      - name: Azure Logout
        run: |
          az logout

