name: Build and Deploy to Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: npm run build

      - name: Upload build to blob storage
        uses: azure/storage-blob-action@v1
        with:
          account: statichostingwebs
          accessKey: ${ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          container: $web
          source: dist

deploy:
       needs: build
        runs-on: ubuntu-latest
         - uses: actions/checkout@v3
         - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          run: az storage blob set-static-websit --account-name statichostingwebs --container $web

