name: Deploy website

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js(18.17.1)
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
      
    - name: Build website
      run: |
        yarn install
        yarn run build
        name: Deployment
        
  Deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALSS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name statichostingwebs --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key --overwrite -d '$web' -s .
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
